### ISSUE TITLE
Migrate code to official "GitHub TypeScript action" template to get typing and jest

### ISSUE THREAD

**Issue by konstantintieber** [leanix/storage-deploy-action#23]
GitHub provides a (in my opinion) very clean TypeScript template for actions: https://github.com/actions/typescript-action

It would be awesome to integrate this template into this storage-deploy-action.

**Comment by aleics-lx** [comment]
Addressed in https://github.com/leanix/storage-deploy-action/pull/33.

**Comment by konstantintieber** [comment]
Thansk @aleics-lx ! I created a follow up for jest: https://github.com/leanix/storage-deploy-action/issues/35
