### ISSUE TITLE
Remove all code related to uploading assets to azure file share

### ISSUE THREAD

**Issue by konstantintieber** [leanix/storage-deploy-action#38]
Since March 15th we’ve switched back from Azure File Share to Azure Blob Storage for serving our frontends ([see this slack thread](https://leanix.slack.com/archives/C7LJARSP2/p1647264245405959)).

Now a large chunk of code in our [storage-deploy-action](https://github.com/leanix/storage-deploy-action) is about making Azure File Storage a more reliable static file hosting solution, such as the only-deploy-changed-files parameter.

→ this can all be removed!

As well as the `az copy` command itself: [link to code](https://github.com/leanix/storage-deploy-action/blob/master/src/index.ts#L341-L405) (for blobstorage we use `az sync`, which comes with a “only upload changed files functionality”).

Workflow inputs to be removed (bonus points if you remove all usages of them before removing them):
- only-deploy-changed-files
- only-blob-upload (used only by SMP teams today)

**Comment by konstantintieber** [comment]
@yae-leanix @perbernhardt please confirm that there's no reason to wait with this anymore. I have the feeling that blobStorage is now here to stay.

**Comment by yae-leanix** [comment]
Agreed. We should drop it for good. Going back to the fileshare should not be an option for us anymore, based on the factors @perbernhardt already mentioned.
